more refactoring

diff --git a/bin/random-wallpaper b/bin/random-wallpaper
--- a/bin/random-wallpaper
+++ b/bin/random-wallpaper
@@ -1,7 +1,34 @@
 #!/bin/bash
 
-cd ~/.local/wallpapers
+if [ -z "${DISPLAY}" ]; then
+  echo "Not running in a graphical environment, exiting..."
+  exit 1
+fi
 
+function notify()
+{
+  urgency="$1"
+  message1="$2"
+  message2="$3"
+
+  # There is a display - use notify-send
+  if [ "$urgency" = "urgent" ]; then
+    # Notify with critical urgency
+    notify-send --urgency critical "$message1" "$message2"
+  else
+    # Notify normally
+    notify-send "$message1" "$message2"
+  fi
+}
+
+WALLPAPER_DIR="${XDG_DATA_HOME}/wallpapers"
+
+if [ ! -d "${WALLPAPER_DIR}" ]; then
+  notify urgent "ERROR" "Wallpapers directory not found at ${XDG_DATA_HOME}/wallpapers"
+  exit 1
+fi
+
+cd ${WALLPAPER_DIR}
 WALLPAPER=$(find $(pwd) -type f | grep -v '.git' | shuf -n 1)
 WALLPAPER=$(readlink -f ${WALLPAPER})
 
