re-organized os services scripts, completed VPN selector script, created askpass script to be used with sudo -A

diff --git a/bin/vpn-selector b/bin/vpn-selector
--- a/bin/vpn-selector
+++ b/bin/vpn-selector
@@ -1,28 +1,93 @@
 #!/bin/bash
 
+WORKING_DIR=$(dirname "$(realpath "$0")")
+SCRIPTS_DIR="${WORKING_DIR}/.."
+
 VPN_CONFIGS_LOCATION="${XDG_CONFIG_HOME}/wireguard"
 
-  if ! [[ -e ${VPN_CONFIGS_LOCATION} && -n "$(ls -A ${VPN_CONFIGS_LOCATION})" ]]; then
+if ! [[ -e ${VPN_CONFIGS_LOCATION} && -n "$(ls -A ${VPN_CONFIGS_LOCATION})" ]]; then
   notify CRITICAL "ERROR" "No VPN configuration files found at \"${VPN_CONFIGS_LOCATION}\""
-  exit
+  exit 1
 fi
 
-notify NORMAL "Please select your preferred VPN server"
+function connect_vpn()
+{
+  # Which VPN server should we connect to?
+  notify NORMAL "Please select your preferred VPN server"
 
-serverChoice=$(ls ${VPN_CONFIGS_LOCATION} | sed 's/\.conf$//' | fuzzel --dmenu -p "Select a VPN server: ")
+  serverChoice=$(ls ${VPN_CONFIGS_LOCATION} | sed 's/\.conf$//' | fuzzel --dmenu -p "Select a VPN server: ")
 
-if [[ -z ${serverChoice} ]]; then
-  notify CRITICAL "ERROR" "Must select a VPN server"
-  exit
-fi
+  if [[ -z ${serverChoice} ]]; then
+    notify CRITICAL "ERROR" "Must select a VPN server"
+    exit 1
+  fi
 
-notify NORMAL "Attempting to connect to VPN server \"${serverChoice}\""
+  # Attempt to connect to user choice of VPN server
+  notify NORMAL "Connecting..." "Attempting to connect to VPN server \"${serverChoice}\""
 
-echo "${XDG_CONFIG_HOME}/wireguard/${serverChoice}.conf"
-wgStatus=$(wg-quick up "${XDG_CONFIG_HOME}/wireguard/${serverChoice}.conf")
+  export SUDO_ASKPASS="${SCRIPTS_DIR}/bin/fuzzel-askpass"
+  sudo -A wg-quick up "${VPN_CONFIGS_LOCATION}/${serverChoice}.conf"
+  wgStatus=$?
 
-if [[ ${wgStatus} -eq 0 ]]; then
-  notify NORMAL "Connection to VPN server \"${serverChoice}\" succeeded."
+  if [[ ${wgStatus} -eq 0 ]]; then
+    notify NORMAL "Connected!" "Connection to VPN server \"${serverChoice}\" succeeded."
+  else
+    notify CRITICAL "ERROR" "Connection to VPN server \"${serverChoice}\" failed."
+    exit 1
+  fi
+}
+
+function disconnect_vpn()
+{
+  # Are you sure you would like to disconnect from VPN?
+  notify NORMAL "Please Confirm" "Are you sure you would like to disconnect from VPN server \"${CONNECTION_NAME}\""
+  yn=$(printf 'Yes\nNo' | fuzzel --dmenu --prompt "Really disconnect? ")
+
+  case ${yn} in
+    Yes)
+      ;;
+    *)
+      notify CRITICAL "Aborting VPN disconnection"
+      exit
+    ;;
+  esac
+
+  # Disconnect from VPN
+  notify NORMAL "Disconnecting..." "Attempting to disconnect from VPN server \"${CONNECTION_NAME}\""
+
+  export SUDO_ASKPASS="${SCRIPTS_DIR}/bin/fuzzel-askpass"
+  sudo -A wg-quick down "${VPN_CONFIGS_LOCATION}/${CONNECTION_NAME}.conf"
+  wgStatus=$?
+
+  if [[ ${wgStatus} -eq 0 ]]; then
+    notify NORMAL "Disconnected!" "Successfully disconnected from VPN server \"${CONNECTION_NAME}\""
+  else
+    notify CRITICAL "ERROR" "Failed to disconnect from VPN server \"${CONNECTION_NAME}\""
+    exit 1
+  fi
+}
+
+CONNECTION_NAME=""
+
+# Check for an active Wireguard VPN connection
+while read -r name uuid type device
+do
+  if [[ ${type} == "wireguard" ]]
+  then
+    while read -r key value
+    do
+      if [[ "${key}" == "ipv4.addresses:" ]]; then
+        CONNECTION_NAME="${name}"
+      fi
+    done < <(nmcli connection show $name)
+  fi
+done < <(nmcli connection show)
+
+if [[ "${CONNECTION_NAME}" == "" ]]; then
+  # If there is no active connection, prompt the user to connect
+  connect_vpn
 else
-  notify CRITICAL "ERROR" "Connection to VPN server \"${serverChoice}\" failed."
+  # If there is an active connection, prompt the user to disconnect
+  disconnect_vpn
 fi
+
