more work on vpn-selector script, now it actually works

diff --git a/bin/vpn-selector b/bin/vpn-selector
--- a/bin/vpn-selector
+++ b/bin/vpn-selector
@@ -2,7 +2,7 @@
 
 VPN_CONFIGS_LOCATION="${XDG_CONFIG_HOME}/wireguard"
 
-if [[ -e ${VPN_CONFIGS_LOCATION} || ! -d ${VPN_CONFIGS_LOCATION} ]]; then
+  if ! [[ -e ${VPN_CONFIGS_LOCATION} && -n "$(ls -A ${VPN_CONFIGS_LOCATION})" ]]; then
   notify CRITICAL "ERROR" "No VPN configuration files found at \"${VPN_CONFIGS_LOCATION}\""
   exit
 fi
@@ -19,10 +19,10 @@ fi
 notify NORMAL "Attempting to connect to VPN server \"${serverChoice}\""
 
 echo "${XDG_CONFIG_HOME}/wireguard/${serverChoice}.conf"
-errorCode=$(wg-quick up "${XDG_CONFIG_HOME}/wireguard/${serverChoice}.conf")
+wgStatus=$(wg-quick up "${XDG_CONFIG_HOME}/wireguard/${serverChoice}.conf")
 
-if echo ${errorCode} | grep -q "successfully activated"; then
+if [[ ${wgStatus} -eq 0 ]]; then
   notify NORMAL "Connection to VPN server \"${serverChoice}\" succeeded."
 else
-  notify CRITICAL "Connection to VPN server \"${serverChoice}\" failed." "Error code ${errorCode}"
+  notify CRITICAL "ERROR" "Connection to VPN server \"${serverChoice}\" failed."
 fi
